[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npx react-scripts build"
]

[start]
cmd = "node server/server.js"
